package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"conan-cli/internal/atomicfile"
)

const generatedMarker = "Generated by conan-cli"

type RecipeKind string

const (
	RecipeConsume RecipeKind = "consume"
	RecipePublish RecipeKind = "publish"
)

type GenerateInput struct {
	Kind        RecipeKind
	Name        string
	Version     string
	BuildSystem string
	QtVersion   string
	Requires    []string
	LibDirs     []string
	IncludeDirs []string
	Force       bool
}

func IsGenerated(dir string) bool {
	return GeneratedKind(dir) != ""
}

func GeneratedKind(dir string) RecipeKind {
	return GeneratedKindAt(filepath.Join(dir, "conanfile.py"))
}

func GeneratedKindAt(path string) RecipeKind {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	text := string(data)
	if !strings.Contains(text, generatedMarker) {
		return ""
	}
	if strings.Contains(text, "kind: publish") {
		return RecipePublish
	}
	if strings.Contains(text, "kind: consume") {
		return RecipeConsume
	}
	return RecipeConsume
}

// PublishRecipeDir is <project>/.conan-cli/recipes/<name> so publish recipes
// never overwrite the consume conanfile at the repository root.
func PublishRecipeDir(projectDir, name string) string {
	return filepath.Join(projectDir, ".conan-cli", "recipes", strings.TrimSpace(name))
}

func PublishRecipePath(projectDir, name string) string {
	return filepath.Join(PublishRecipeDir(projectDir, name), "conanfile.py")
}

func Generate(dir string, input GenerateInput) (string, error) {
	if input.Kind != RecipeConsume && input.Kind != RecipePublish {
		return "", fmt.Errorf("unknown recipe kind %q", input.Kind)
	}
	if strings.TrimSpace(input.Name) == "" {
		input.Name = filepath.Base(dir)
	}
	if strings.TrimSpace(input.Version) == "" {
		input.Version = "1.0"
	}
	if input.Kind == RecipePublish {
		return generatePublish(dir, input)
	}
	pyPath := filepath.Join(dir, "conanfile.py")
	if _, err := os.Stat(pyPath); err == nil && !input.Force {
		if existing := GeneratedKind(dir); existing == "" {
			return "", fmt.Errorf("已有手工 conanfile.py，不会覆盖。确认后可强制重新生成")
		} else if existing != input.Kind {
			return "", fmt.Errorf("已有%s配方，生成%s会覆盖。确认后可强制重新生成", kindLabel(existing), kindLabel(input.Kind))
		}
	}
	if err := atomicfile.Write(pyPath, []byte(consumeRecipe(input)), 0o644); err != nil {
		return "", fmt.Errorf("write conanfile.py: %w", err)
	}
	txtPath := filepath.Join(dir, "conanfile.txt")
	if _, err := os.Stat(txtPath); err == nil {
		_ = os.Remove(txtPath)
	}
	return pyPath, nil
}

func generatePublish(projectDir string, input GenerateInput) (string, error) {
	pyPath := PublishRecipePath(projectDir, input.Name)
	if err := os.MkdirAll(filepath.Dir(pyPath), 0o755); err != nil {
		return "", fmt.Errorf("create publish recipe directory: %w", err)
	}
	if _, err := os.Stat(pyPath); err == nil && !input.Force {
		if existing := GeneratedKindAt(pyPath); existing == "" {
			return "", fmt.Errorf("已有手工发布配方 %s，不会覆盖。确认后可强制重新生成", pyPath)
		}
	}
	if err := atomicfile.Write(pyPath, []byte(publishRecipe(input)), 0o644); err != nil {
		return "", fmt.Errorf("write publish recipe: %w", err)
	}
	return pyPath, nil
}

func consumeRecipe(input GenerateInput) string {
	var req strings.Builder
	if len(input.Requires) == 0 {
		req.WriteString("    requires = (\n    )\n")
	} else {
		req.WriteString("    requires = (\n")
		for _, item := range input.Requires {
			req.WriteString("        \"" + item + "\",\n")
		}
		req.WriteString("    )\n")
	}
	options := "    default_options = {}\n"
	if strings.TrimSpace(input.QtVersion) != "" {
		options = "    default_options = {\n        \"*:qt_version\": \"" + strings.TrimSpace(input.QtVersion) + "\",\n    }\n"
	}
	generate := consumeGenerateQMake
	if strings.EqualFold(input.BuildSystem, "cmake") {
		generate = consumeGenerateCMake
	}
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: consume
from conan import ConanFile


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
%s%s
%s
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, req.String(), options, generate)
}

const consumeGenerateQMake = `    def generate(self):
        includedirs, libdirs, libs, defines = [], [], [], []
        for _, dep in self.dependencies.items():
            cpp_info = dep.cpp_info.aggregated_components()
            includedirs += cpp_info.includedirs
            libdirs += cpp_info.libdirs
            libs += cpp_info.libs
            defines += cpp_info.defines
        lines = [
            "# Generated by conan-cli - do not edit",
            "INCLUDEPATH += " + " ".join('"%s"' % p for p in includedirs),
            "LIBS += " + " ".join('"-L%s"' % p for p in libdirs) + " " + " ".join("-l%s" % l for l in libs),
            "DEFINES += " + " ".join(defines),
            "QMAKE_LFLAGS += " + " ".join('"-Wl,-rpath,%s"' % p for p in libdirs),
        ]
        with open("conanbuildinfo.pri", "w") as fh:
            fh.write("\n".join(lines) + "\n")
`

const consumeGenerateCMake = `    def generate(self):
        from conan.tools.cmake import CMakeDeps, CMakeToolchain
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()
`

func pythonStringList(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q", filepath.ToSlash(value)))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func publishQtOptions(qt string) string {
	if strings.TrimSpace(qt) == "" {
		return `    options = {
        "shared": [True, False],
        "fPIC": [True, False],
    }
    default_options = {"shared": True, "fPIC": True}`
	}
	return fmt.Sprintf(`    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "qt_version": [%s],
    }
    default_options = {"shared": True, "fPIC": True, "qt_version": %q}`, qtOptionList(qt), qt)
}

func publishRecipe(input GenerateInput) string {
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: publish
# 预编译发布：请先用对应套件编好库，再点发布。不会在发布时调用 qmake/cmake。
from conan import ConanFile
from conan.tools.files import copy
import os


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
%s
    _lib_dirs = %s
    _include_dirs = %s

    def export_sources(self):
        pass

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        pass

    def _project_root(self):
        return os.path.abspath(os.path.join(self.recipe_folder, "..", "..", ".."))

    def _join_rel(self, root, rel):
        return os.path.join(root, *rel.split("/"))

    def _lib_roots(self, root):
        if self._lib_dirs:
            return [self._join_rel(root, rel) for rel in self._lib_dirs]
        bt = str(self.settings.build_type)
        return [
            os.path.join(root, "lib", bt),
            os.path.join(root, "lib", bt.lower()),
            os.path.join(root, "lib"),
            os.path.join(root, "bin", bt),
            os.path.join(root, "bin"),
        ]

    def package(self):
        root = self._project_root()
        dst_inc = os.path.join(self.package_folder, "include")
        dst_lib = os.path.join(self.package_folder, "lib")
        dst_bin = os.path.join(self.package_folder, "bin")
        searched = []
        if self._include_dirs:
            for rel in self._include_dirs:
                inc = self._join_rel(root, rel)
                if os.path.isdir(inc):
                    copy(self, "*", inc, dst_inc, keep_path=True)
        else:
            copy(self, "*.h", root, dst_inc, keep_path=True)
            copy(self, "*.hpp", root, dst_inc, keep_path=True)
            inc = os.path.join(root, "include")
            if os.path.isdir(inc):
                copy(self, "*", inc, dst_inc, keep_path=True)
        for libroot in self._lib_roots(root):
            searched.append(libroot)
            if not os.path.isdir(libroot):
                continue
            copy(self, "*.so*", libroot, dst_lib, keep_path=False)
            copy(self, "*.a", libroot, dst_lib, keep_path=False)
            copy(self, "*.lib", libroot, dst_lib, keep_path=False)
            copy(self, "*.dylib", libroot, dst_lib, keep_path=False)
            copy(self, "*.dll", libroot, dst_bin, keep_path=False)
        libdir = os.path.join(self.package_folder, "lib")
        bindir = os.path.join(self.package_folder, "bin")
        has_lib = False
        for folder in (libdir, bindir):
            if os.path.isdir(folder) and any(not name.startswith(".") for name in os.listdir(folder)):
                has_lib = True
        if not has_lib:
            raise Exception("未找到已编译的库。已查找：%%s。请先用发布页同一套系统/编译器/Qt/Debug|Release 在本机编好，再发布。" %% (", ".join(searched) if searched else "lib/, bin/"))

    def package_info(self):
        names = []
        libdir = os.path.join(self.package_folder, "lib")
        if os.path.isdir(libdir):
            for fn in sorted(os.listdir(libdir)):
                base = fn[3:] if fn.startswith("lib") else fn
                if ".so." in base:
                    base = base.split(".so")[0]
                else:
                    for ext in (".so", ".a", ".lib", ".dylib"):
                        if base.endswith(ext):
                            base = base[:-len(ext)]
                            break
                    else:
                        continue
                if base and base not in names:
                    names.append(base)
        self.cpp_info.libs = names or [str(self.name)]
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, publishQtOptions(input.QtVersion), pythonStringList(input.LibDirs), pythonStringList(input.IncludeDirs))
}

func qtOptionList(current string) string {
	seen := map[string]bool{}
	var values []string
	for _, item := range []string{current, "5.15", "6.5", "6.8"} {
		item = strings.TrimSpace(item)
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		values = append(values, `"`+item+`"`)
	}
	return strings.Join(values, ", ")
}

func kindLabel(kind RecipeKind) string {
	if kind == RecipePublish {
		return "发布"
	}
	return "消费"
}

func pythonClass(name string) string {
	var parts []string
	var current strings.Builder
	flush := func() {
		piece := current.String()
		current.Reset()
		if piece == "" {
			return
		}
		runes := []rune(piece)
		runes[0] = unicode.ToUpper(runes[0])
		parts = append(parts, string(runes))
	}
	for _, r := range name {
		if r == '-' || r == '_' || r == '.' || r == ' ' {
			flush()
			continue
		}
		current.WriteRune(r)
	}
	flush()
	if len(parts) == 0 {
		return "Package"
	}
	out := strings.Join(parts, "")
	if unicode.IsDigit([]rune(out)[0]) {
		out = "Pkg" + out
	}
	return out
}
