package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"conan-cli/internal/atomicfile"
)

const generatedMarker = "Generated by conan-cli"

type RecipeKind string

const (
	RecipeConsume RecipeKind = "consume"
	RecipePublish RecipeKind = "publish"
)

type GenerateInput struct {
	Kind        RecipeKind
	Name        string
	Version     string
	BuildSystem string
	QtVersion   string
	Requires    []string
	Force       bool
}

func IsGenerated(dir string) bool {
	return GeneratedKind(dir) != ""
}

func GeneratedKind(dir string) RecipeKind {
	data, err := os.ReadFile(filepath.Join(dir, "conanfile.py"))
	if err != nil {
		return ""
	}
	text := string(data)
	if !strings.Contains(text, generatedMarker) {
		return ""
	}
	if strings.Contains(text, "kind: publish") {
		return RecipePublish
	}
	if strings.Contains(text, "kind: consume") {
		return RecipeConsume
	}
	return RecipeConsume
}

func Generate(dir string, input GenerateInput) (string, error) {
	if input.Kind != RecipeConsume && input.Kind != RecipePublish {
		return "", fmt.Errorf("unknown recipe kind %q", input.Kind)
	}
	if strings.TrimSpace(input.Name) == "" {
		input.Name = filepath.Base(dir)
	}
	if strings.TrimSpace(input.Version) == "" {
		input.Version = "1.0"
	}
	pyPath := filepath.Join(dir, "conanfile.py")
	if _, err := os.Stat(pyPath); err == nil && !input.Force {
		if existing := GeneratedKind(dir); existing == "" {
			return "", fmt.Errorf("已有手工 conanfile.py，不会覆盖。确认后可强制重新生成")
		} else if existing != input.Kind {
			return "", fmt.Errorf("已有%s配方，生成%s会覆盖。确认后可强制重新生成", kindLabel(existing), kindLabel(input.Kind))
		}
	}
	var body string
	if input.Kind == RecipePublish {
		body = publishRecipe(input)
	} else {
		body = consumeRecipe(input)
	}
	if err := atomicfile.Write(pyPath, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("write conanfile.py: %w", err)
	}
	txtPath := filepath.Join(dir, "conanfile.txt")
	if _, err := os.Stat(txtPath); err == nil {
		_ = os.Remove(txtPath)
	}
	return pyPath, nil
}

func consumeRecipe(input GenerateInput) string {
	var req strings.Builder
	if len(input.Requires) == 0 {
		req.WriteString("    requires = (\n    )\n")
	} else {
		req.WriteString("    requires = (\n")
		for _, item := range input.Requires {
			req.WriteString("        \"" + item + "\",\n")
		}
		req.WriteString("    )\n")
	}
	options := "    default_options = {}\n"
	if strings.TrimSpace(input.QtVersion) != "" {
		options = "    default_options = {\n        \"*:qt_version\": \"" + strings.TrimSpace(input.QtVersion) + "\",\n    }\n"
	}
	generate := consumeGenerateQMake
	if strings.EqualFold(input.BuildSystem, "cmake") {
		generate = consumeGenerateCMake
	}
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: consume
from conan import ConanFile


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
%s%s
%s
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, req.String(), options, generate)
}

const consumeGenerateQMake = `    def generate(self):
        includedirs, libdirs, libs, defines = [], [], [], []
        for _, dep in self.dependencies.items():
            cpp_info = dep.cpp_info.aggregated_components()
            includedirs += cpp_info.includedirs
            libdirs += cpp_info.libdirs
            libs += cpp_info.libs
            defines += cpp_info.defines
        lines = [
            "# Generated by conan-cli - do not edit",
            "INCLUDEPATH += " + " ".join('"%s"' % p for p in includedirs),
            "LIBS += " + " ".join('"-L%s"' % p for p in libdirs) + " " + " ".join("-l%s" % l for l in libs),
            "DEFINES += " + " ".join(defines),
            "QMAKE_LFLAGS += " + " ".join('"-Wl,-rpath,%s"' % p for p in libdirs),
        ]
        with open("conanbuildinfo.pri", "w") as fh:
            fh.write("\n".join(lines) + "\n")
`

const consumeGenerateCMake = `    def generate(self):
        from conan.tools.cmake import CMakeDeps, CMakeToolchain
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()
`

func publishRecipe(input GenerateInput) string {
	qt := strings.TrimSpace(input.QtVersion)
	if qt == "" {
		qt = "6.8"
	}
	choices := qtOptionList(qt)
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: publish
# 预编译发布：请先用对应套件编好库，再点发布。不会在发布时调用 qmake/cmake。
from conan import ConanFile
from conan.tools.files import copy
import os


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "qt_version": [%s],
    }
    default_options = {"shared": True, "fPIC": True, "qt_version": %q}

    def export_sources(self):
        copy(self, "*", src=self.recipe_folder, dst=self.export_sources_folder, excludes=[
            "test_package", "test_package/*", ".git", ".git/*", ".conan-cli", ".conan-cli/*",
            "build", "build/*", "example", "example/*",
            "*.user", "*.stash", "Makefile", "Makefile.*", "*.o", "moc_*", "ui_*.h",
        ])

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        pass

    def _lib_roots(self, root):
        bt = str(self.settings.build_type)
        return [
            os.path.join(root, "lib", bt),
            os.path.join(root, "lib", bt.lower()),
            os.path.join(root, "lib"),
            os.path.join(root, "bin", bt),
            os.path.join(root, "bin"),
        ]

    def package(self):
        roots = [self.source_folder]
        recipe = getattr(self, "recipe_folder", None)
        if recipe and recipe not in roots:
            roots.append(recipe)
        dst_inc = os.path.join(self.package_folder, "include")
        dst_lib = os.path.join(self.package_folder, "lib")
        dst_bin = os.path.join(self.package_folder, "bin")
        for root in roots:
            copy(self, "*.h", root, dst_inc, keep_path=True)
            copy(self, "*.hpp", root, dst_inc, keep_path=True)
            inc = os.path.join(root, "include")
            if os.path.isdir(inc):
                copy(self, "*", inc, dst_inc, keep_path=True)
            for libroot in self._lib_roots(root):
                if not os.path.isdir(libroot):
                    continue
                copy(self, "*.so*", libroot, dst_lib, keep_path=False)
                copy(self, "*.a", libroot, dst_lib, keep_path=False)
                copy(self, "*.lib", libroot, dst_lib, keep_path=False)
                copy(self, "*.dylib", libroot, dst_lib, keep_path=False)
                copy(self, "*.dll", libroot, dst_bin, keep_path=False)
        libdir = os.path.join(self.package_folder, "lib")
        bindir = os.path.join(self.package_folder, "bin")
        has_lib = False
        for folder in (libdir, bindir):
            if os.path.isdir(folder) and any(not name.startswith(".") for name in os.listdir(folder)):
                has_lib = True
        if not has_lib:
            raise Exception("未找到已编译的库（例如 lib/*.so、lib/*.a、lib/*.dll）。请先用发布页同一套系统/编译器/Qt/Debug|Release 在本机编好，再发布。")

    def package_info(self):
        names = []
        libdir = os.path.join(self.package_folder, "lib")
        if os.path.isdir(libdir):
            for fn in sorted(os.listdir(libdir)):
                base = fn[3:] if fn.startswith("lib") else fn
                if ".so." in base:
                    base = base.split(".so")[0]
                else:
                    for ext in (".so", ".a", ".lib", ".dylib"):
                        if base.endswith(ext):
                            base = base[:-len(ext)]
                            break
                    else:
                        continue
                if base and base not in names:
                    names.append(base)
        self.cpp_info.libs = names or [str(self.name)]
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, choices, qt)
}

func qtOptionList(current string) string {
	seen := map[string]bool{}
	var values []string
	for _, item := range []string{current, "5.15", "6.5", "6.8"} {
		item = strings.TrimSpace(item)
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		values = append(values, `"`+item+`"`)
	}
	return strings.Join(values, ", ")
}

func kindLabel(kind RecipeKind) string {
	if kind == RecipePublish {
		return "发布"
	}
	return "消费"
}

func pythonClass(name string) string {
	var parts []string
	var current strings.Builder
	flush := func() {
		piece := current.String()
		current.Reset()
		if piece == "" {
			return
		}
		runes := []rune(piece)
		runes[0] = unicode.ToUpper(runes[0])
		parts = append(parts, string(runes))
	}
	for _, r := range name {
		if r == '-' || r == '_' || r == '.' || r == ' ' {
			flush()
			continue
		}
		current.WriteRune(r)
	}
	flush()
	if len(parts) == 0 {
		return "Package"
	}
	out := strings.Join(parts, "")
	if unicode.IsDigit([]rune(out)[0]) {
		out = "Pkg" + out
	}
	return out
}
