package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const generatedMarker = "Generated by conan-cli"

type RecipeKind string

const (
	RecipeConsume RecipeKind = "consume"
	RecipePublish RecipeKind = "publish"
)

type GenerateInput struct {
	Kind        RecipeKind
	Name        string
	Version     string
	BuildSystem string
	QtVersion   string
	Requires    []string
	Force       bool
}

func IsGenerated(dir string) bool {
	return GeneratedKind(dir) != ""
}

func GeneratedKind(dir string) RecipeKind {
	data, err := os.ReadFile(filepath.Join(dir, "conanfile.py"))
	if err != nil {
		return ""
	}
	text := string(data)
	if !strings.Contains(text, generatedMarker) {
		return ""
	}
	if strings.Contains(text, "kind: publish") {
		return RecipePublish
	}
	if strings.Contains(text, "kind: consume") {
		return RecipeConsume
	}
	return RecipeConsume
}

func Generate(dir string, input GenerateInput) (string, error) {
	if input.Kind != RecipeConsume && input.Kind != RecipePublish {
		return "", fmt.Errorf("unknown recipe kind %q", input.Kind)
	}
	if strings.TrimSpace(input.Name) == "" {
		input.Name = filepath.Base(dir)
	}
	if strings.TrimSpace(input.Version) == "" {
		input.Version = "1.0"
	}
	pyPath := filepath.Join(dir, "conanfile.py")
	if _, err := os.Stat(pyPath); err == nil && !input.Force {
		if existing := GeneratedKind(dir); existing == "" {
			return "", fmt.Errorf("已有手工 conanfile.py，不会覆盖。确认后可强制重新生成")
		} else if existing != input.Kind {
			return "", fmt.Errorf("已有%s配方，生成%s会覆盖。确认后可强制重新生成", kindLabel(existing), kindLabel(input.Kind))
		}
	}
	var body string
	if input.Kind == RecipePublish {
		body = publishRecipe(input)
	} else {
		body = consumeRecipe(input)
	}
	if err := writeAtomic(pyPath, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("write conanfile.py: %w", err)
	}
	txtPath := filepath.Join(dir, "conanfile.txt")
	if _, err := os.Stat(txtPath); err == nil {
		_ = os.Remove(txtPath)
	}
	return pyPath, nil
}

func consumeRecipe(input GenerateInput) string {
	var req strings.Builder
	if len(input.Requires) == 0 {
		req.WriteString("    requires = (\n    )\n")
	} else {
		req.WriteString("    requires = (\n")
		for _, item := range input.Requires {
			req.WriteString("        \"" + item + "\",\n")
		}
		req.WriteString("    )\n")
	}
	options := "    default_options = {}\n"
	if strings.TrimSpace(input.QtVersion) != "" {
		options = "    default_options = {\n        \"*:qt_version\": \"" + strings.TrimSpace(input.QtVersion) + "\",\n    }\n"
	}
	generate := consumeGenerateQMake
	if strings.EqualFold(input.BuildSystem, "cmake") {
		generate = consumeGenerateCMake
	}
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: consume
from conan import ConanFile


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
%s%s
%s
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, req.String(), options, generate)
}

const consumeGenerateQMake = `    def generate(self):
        includedirs, libdirs, libs, defines = [], [], [], []
        for _, dep in self.dependencies.items():
            cpp_info = dep.cpp_info.aggregated_components()
            includedirs += cpp_info.includedirs
            libdirs += cpp_info.libdirs
            libs += cpp_info.libs
            defines += cpp_info.defines
        lines = [
            "# Generated by conan-cli - do not edit",
            "INCLUDEPATH += " + " ".join('"%s"' % p for p in includedirs),
            "LIBS += " + " ".join('"-L%s"' % p for p in libdirs) + " " + " ".join("-l%s" % l for l in libs),
            "DEFINES += " + " ".join(defines),
            "QMAKE_LFLAGS += " + " ".join('"-Wl,-rpath,%s"' % p for p in libdirs),
        ]
        with open("conanbuildinfo.pri", "w") as fh:
            fh.write("\n".join(lines) + "\n")
`

const consumeGenerateCMake = `    def generate(self):
        from conan.tools.cmake import CMakeDeps, CMakeToolchain
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()
`

func publishRecipe(input GenerateInput) string {
	qt := strings.TrimSpace(input.QtVersion)
	if qt == "" {
		qt = "6.8"
	}
	choices := qtOptionList(qt)
	return fmt.Sprintf(`# %s. Regenerating from the plugin will overwrite this file.
# kind: publish
from conan import ConanFile
from conan.tools.files import copy
import glob
import os


class %sConan(ConanFile):
    name = %q
    version = %q
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "qt_version": [%s],
    }
    default_options = {"shared": True, "fPIC": True, "qt_version": %q}
    exports_sources = "*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        build_type = str(self.settings.build_type)
        cmake_lists = os.path.join(self.source_folder, "CMakeLists.txt")
        if os.path.exists(cmake_lists):
            self.run('cmake -S "%%s" -B "%%s" -DCMAKE_BUILD_TYPE=%%s' %% (self.source_folder, self.build_folder, build_type))
            self.run('cmake --build "%%s" --config %%s' %% (self.build_folder, build_type))
            return
        pro_files = glob.glob(os.path.join(self.source_folder, "*.pro"))
        if not pro_files:
            raise Exception("未找到 CMakeLists.txt 或 .pro，无法自动构建")
        libkind = "shared" if self.options.shared else "staticlib"
        qmake_mode = "debug" if build_type == "Debug" else "release"
        self.run('qmake "%%s" CONFIG+=%%s CONFIG+=%%s' %% (pro_files[0], libkind, qmake_mode), cwd=self.build_folder)
        make = "nmake" if str(self.settings.os) == "Windows" else "make -j4"
        self.run(make, cwd=self.build_folder)

    def package(self):
        copy(self, "*.h", self.source_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.hpp", self.source_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.so*", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, "*.lib", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, "*.dll", self.build_folder, os.path.join(self.package_folder, "bin"), keep_path=False)
        copy(self, "*.dylib", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs = [self.name]
`, generatedMarker, pythonClass(input.Name), input.Name, input.Version, choices, qt)
}

func qtOptionList(current string) string {
	seen := map[string]bool{}
	var values []string
	for _, item := range []string{current, "5.15", "6.5", "6.8"} {
		item = strings.TrimSpace(item)
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		values = append(values, `"`+item+`"`)
	}
	return strings.Join(values, ", ")
}

func kindLabel(kind RecipeKind) string {
	if kind == RecipePublish {
		return "发布"
	}
	return "消费"
}

func pythonClass(name string) string {
	var parts []string
	var current strings.Builder
	flush := func() {
		piece := current.String()
		current.Reset()
		if piece == "" {
			return
		}
		runes := []rune(piece)
		runes[0] = unicode.ToUpper(runes[0])
		parts = append(parts, string(runes))
	}
	for _, r := range name {
		if r == '-' || r == '_' || r == '.' || r == ' ' {
			flush()
			continue
		}
		current.WriteRune(r)
	}
	flush()
	if len(parts) == 0 {
		return "Package"
	}
	out := strings.Join(parts, "")
	if unicode.IsDigit([]rune(out)[0]) {
		out = "Pkg" + out
	}
	return out
}
