package manifest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEnsureTextCreatesRecipe(t *testing.T) {
	dir := t.TempDir()
	path, created, err := EnsureText(dir, "qmake")
	if err != nil || !created {
		t.Fatalf("created=%v err=%v", created, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "PkgConfigDeps") {
		t.Fatalf("unexpected generators: %s", data)
	}
}

func TestAddToTextManifest(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.txt")
	content := "[requires]\nfmt/10.2.1\n\n[generators]\nCMakeDeps\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "zlib/1.3"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "zlib/1.3") {
		t.Fatalf("manifest does not contain dependency: %s", text)
	}
}

func TestAddToStaticPythonRecipe(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := "from conan import ConanFile\n\nclass Pkg(ConanFile):\n    requires = (\n        \"fmt/10.2.1\",\n    )\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "zlib/1.3"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, `"zlib/1.3"`) {
		t.Fatalf("recipe does not contain dependency: %s", text)
	}
}

func TestRejectDynamicPythonRequirements(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := "class Pkg:\n    def requirements(self):\n        self.requires(\"fmt/10.2.1\")\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "zlib/1.3"); err == nil {
		t.Fatal("Add succeeded for dynamic requirements")
	}
}

func TestRejectDynamicPythonRequirementsWithSpacing(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := "class Pkg:\n    def requirements (self):\n        self.requires(\"fmt/10.2.1\")\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "zlib/1.3"); err == nil {
		t.Fatal("Add succeeded for dynamic requirements with spacing")
	}
}

func TestAddToScalarPythonRecipe(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := "class Pkg(ConanFile):\n    requires = \"fmt/10.2.1\"\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "zlib/1.3"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "requires = (") || !strings.Contains(text, `"zlib/1.3"`) {
		t.Fatalf("scalar recipe was not converted: %s", text)
	}
}

func TestAddToEmptyTupleRecipe(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := `# Generated by conan-cli
# kind: consume
from conan import ConanFile

class ConanDemoConan(ConanFile):
    name = "conan-demo"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    requires = ()
    default_options = {}
`
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	deps, err := Dependencies(dir)
	if err != nil || len(deps) != 0 {
		t.Fatalf("empty tuple deps=%#v err=%v", deps, err)
	}
	if _, err := Add(dir, "qtutils/1.0"); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if !strings.Contains(text, `"qtutils/1.0"`) || !strings.Contains(text, "requires = (") {
		t.Fatalf("empty tuple not expanded: %s", text)
	}
	deps, err = Dependencies(dir)
	if err != nil || len(deps) != 1 || deps[0] != "qtutils/1.0" {
		t.Fatalf("deps after add = %#v err=%v", deps, err)
	}
}

func TestAddInsertsRequiresWhenMissing(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	content := "from conan import ConanFile\nclass Pkg(ConanFile):\n    name = \"lib\"\n    version = \"1.0\"\n    settings = \"os\", \"compiler\", \"build_type\", \"arch\"\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Add(dir, "qtutils/1.0"); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), `"qtutils/1.0"`) {
		t.Fatalf("missing requires not inserted: %s", data)
	}
}

func TestDependenciesWithoutRequires(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.py")
	if err := os.WriteFile(path, []byte("from conan import ConanFile\nclass Pkg(ConanFile):\n    name = \"lib\"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	deps, err := Dependencies(dir)
	if err != nil || len(deps) != 0 {
		t.Fatalf("deps=%#v err=%v", deps, err)
	}
}

func TestDependenciesReadsTextManifest(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "conanfile.txt")
	content := "[requires]\nfmt/10.2.1\n# comment\nzlib/1.3\n\n[generators]\nCMakeDeps\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	dependencies, err := Dependencies(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(dependencies) != 2 || dependencies[0] != "fmt/10.2.1" || dependencies[1] != "zlib/1.3" {
		t.Fatalf("dependencies = %#v", dependencies)
	}
}
